"""empty message

Revision ID: 2b9b12d6b02e
Revises: 5a6df4dbcc5c
Create Date: 2019-11-22 16:11:32.608962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b9b12d6b02e'
down_revision = '5a6df4dbcc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_end_date', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('event_end_time', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('event_start_date', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('event_start_time', sa.DateTime(), nullable=False))
    op.drop_column('events', 'event_end')
    op.drop_column('events', 'event_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('event_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'event_start_time')
    op.drop_column('events', 'event_start_date')
    op.drop_column('events', 'event_end_time')
    op.drop_column('events', 'event_end_date')
    # ### end Alembic commands ###
