"""empty message

Revision ID: 459d0047b2a0
Revises: c8b79d1ded4d
Create Date: 2019-11-21 14:50:12.075200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459d0047b2a0'
down_revision = 'c8b79d1ded4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
